/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package scale_legends;
import java.net.URL;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class App extends Application{
    public static void main(String[] args) {
        Application.launch(args);
    }

    @Override
    public void start(Stage stage) throws Exception {
        URL url =  ClassLoader.getSystemResource("scale_legends/assets/Login.fxml");
        FXMLLoader loader = new FXMLLoader(url);
        Parent root = loader.load();
        Scene mainScene = new Scene(root);

        DataBaseHandler connection = DataBaseHandler.getInstance();
        
        stage.setTitle("Scale Legends");
        stage.setScene(mainScene);
        stage.show();
    }
}
