/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package scale_legends;
import javafx.application.Application;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.input.KeyCode;
import javafx.scene.input.KeyCodeCombination;
import javafx.scene.input.KeyCombination;
import javafx.scene.input.KeyEvent;
import javafx.scene.paint.Color;
import javafx.stage.Stage;

public class App extends Application{
    final KeyCombination FullScreenKeyCombo = new KeyCodeCombination(KeyCode.F11);
    public static void main(String[] args) {
        Application.launch(args);
    }

    @Override
    public void start(Stage stage) throws Exception {
        Group root = new Group();
        Scene mainScene = new Scene(root, Color.DARKORANGE);
        
        stage.setTitle("Exemplu");
        //stage.setResizable(false);
        stage.setFullScreen(true);
        stage.setFullScreenExitHint("Acesta este un exemplu și trebuie tratat caatare!\nApasa tasta q pentru a eși din Fullscren");
        stage.setFullScreenExitKeyCombination(KeyCombination.valueOf("q"));
        mainScene.addEventHandler(KeyEvent.KEY_PRESSED, event -> {

            if(FullScreenKeyCombo.match(event)) {

               stage.setFullScreen(!stage.isFullScreen());

            }
         });

        stage.setScene(mainScene);
        stage.show();
        
    }
}
